language: go
go:
- tip
env:
  - m890goYllXpW/jO6yJL+4xr3Dt+SG1M36Ep9HIEe4HTGNa2QhMEvoDpk2WgiGGbAHwHplE0mpo2U6PtK5sZAU0OMbSXkVEFvjL1B2TWwCSxJc1+fVNHSFfxH5Z2qvgAkr+dTCHBhu1txFtdGljxYlb1ETVuV1wOZIv8mRObs0Z8=
  - TwxeET2wUvblWa4MBL6wCgWw/ehwKANo0/2hiZPGfXVElWdqZUulfO8CeqqwvDyTCAyjlSEnU+KBnI5w2FqRvuC/hmMsVqwFFrjLoRCPBVYsKbBpA4mCpQMA12zxB80jrPnMYtlyaIV0FdlCp+j9YdB3qGCUyRhMZ8fy5wY88JA=
  - BT6seFnjMj3lsj5tqHUR2HvaCN6erhqT65P30gavZGvBj/OqpwWNuw4XNP4FCImd+OnN4pAmtPJlJ8STR+d2VW8al8tmupFX4a351/9G4XCEtm/EO6cSNMSFoxQy0JTRQrOWF1/WLBNILb04nipYZV7CbsPrjlkquZfGeDozUcE=
  - TEST_COINBASE_OFFSET: 30
